version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pytorch-app-local"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vczkj3abfc5w"
s3_prefix = "pytorch-app-local"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=507922848584.dkr.ecr.us-east-1.amazonaws.com/pytorch-app-local"]
